/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user (with embedded settings) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user with settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll for user updates (HTTP fallback) */
        get: {
            parameters: {
                query?: {
                    last_seq?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updates wrapper with pagination cursor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updates: components["schemas"]["Update"][];
                            /** Format: int64 */
                            max_seq: number;
                            has_more: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available templates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of templates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Template"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get template by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Template detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Template"];
                    };
                };
                /** @description Template not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a project from a template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description Created project */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List current user's projects */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of projects */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Update a project */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        config?: Record<string, never>;
                    };
                };
            };
            responses: {
                /** @description Updated project */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a project */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Project deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Project not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversations in a project */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of conversations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a conversation in a project */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title?: string;
                    };
                };
            };
            responses: {
                /** @description Created conversation */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: string;
                            project_id?: string;
                            user_id?: string;
                            title?: string;
                            status?: string;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update conversation status (archive, etc.) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description New conversation status (e.g., "archived") */
                        status: string;
                    };
                };
            };
            responses: {
                /** @description Updated conversation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                /** @description Conversation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Delete a conversation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Conversation deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conversation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a conversation (title only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description New conversation title */
                        title: string;
                    };
                };
            };
            responses: {
                /** @description Updated conversation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Conversation"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conversation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/conversations/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List conversation members */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of members */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Member"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/compact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compact a conversation (summarize and create new conversation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Compaction started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            conversation_id: string;
                            status: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages in a conversation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"][];
                    };
                };
            };
        };
        put?: never;
        /** Send a message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Message created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            conversation_id?: string;
                            message_id?: string;
                            seq?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop active streaming in a conversation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Streaming stopped */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer an interrupted human-in-the-loop question */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Eino checkpoint ID for resuming the agent run */
                        checkpoint_id: string;
                        /** @description Eino interrupt signal ID for targeted resume */
                        interrupt_id: string;
                        /** @description User's answer text */
                        answer: string;
                    };
                };
            };
            responses: {
                /** @description Agent resumed with user's answer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid request or HITL already answered */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conversation or HITL request not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/hitl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending human-in-the-loop requests for a conversation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of pending HITL requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HumanInTheLoop"][];
                    };
                };
                /** @description Conversation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List permission requests for a conversation */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "answered";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of permission requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HumanInPermission"][];
                    };
                };
                /** @description Conversation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/permissions/{permId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a permission request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    permId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        checkpoint_id: string;
                        interrupt_id: string;
                        /** @enum {string} */
                        decision: "approved" | "approved_exact" | "approved_wildcard" | "denied";
                    };
                };
            };
            responses: {
                /** @description Permission answered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Already answered or invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Permission request not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List todos for a conversation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of todos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Todo"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a todo item */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Created todo */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Todo"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a todo item */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Todo not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a todo item */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content?: string;
                        completed?: boolean;
                    };
                };
            };
            responses: {
                /** @description Updated todo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Todo"];
                    };
                };
                /** @description Todo not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/conversations/{id}/cron-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cron tasks for a conversation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of cron tasks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronTask"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a cron task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        content: string;
                        schedule: string;
                        /**
                         * @default user
                         * @enum {string}
                         */
                        sender_role?: "assistant" | "user" | "system" | "tool";
                    };
                };
            };
            responses: {
                /** @description Created cron task */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronTask"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{id}/cron-tasks/{taskId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a cron task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    taskId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task cancelled */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Task not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        /** Update settings */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        model_tier?: "haiku" | "sonnet" | "opus";
                        /** @enum {string} */
                        locale?: "en" | "zh";
                        /** @enum {string} */
                        theme?: "light" | "dark";
                    };
                };
            };
            responses: {
                /** @description Updated settings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available AI models */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of model info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            models: {
                                name: string;
                                base_url: string;
                                model: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: uuid */
            id: string;
            name?: string;
            avatar_url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            name?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            settings: components["schemas"]["Settings"];
        };
        Template: {
            id: string;
            name: string;
            description: string;
            tags?: string[];
            /** @enum {string} */
            difficulty?: "beginner" | "intermediate" | "advanced";
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            template_id: string;
            name: string;
            config?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
        };
        Conversation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            user_id: string;
            title?: string;
            summary?: string;
            status?: string;
            last_preview?: string;
            message_count?: number;
            latest_seq?: number;
            member_count?: number;
            token_prompt?: number;
            token_completion?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Message: {
            id: string;
            conversation_id: string;
            seq: number;
            /** @enum {string} */
            sender_role: "user" | "assistant" | "system" | "tool";
            sender_id?: string;
            content: string;
            reason_content?: string;
            metadata?: {
                [key: string]: unknown;
            };
            finish_reason?: string | null;
            error_message?: string | null;
            duration_ms?: number | null;
            token_prompt?: number;
            token_completion?: number;
            /** Format: date-time */
            created_at?: string;
            reply_to_seq?: number;
            mentioned_members?: string[];
            tool_calling?: {
                /** @description Tool call input arguments */
                input?: {
                    [key: string]: unknown;
                };
                /** @description Tool call output result */
                output?: string;
            } | null;
            /** Format: date-time */
            updated_at?: string;
        };
        Settings: {
            /** @enum {string} */
            model_tier?: "haiku" | "sonnet" | "opus";
            /** @enum {string} */
            locale?: "en" | "zh";
            /** @enum {string} */
            theme?: "light" | "dark";
            /** Format: date-time */
            updated_at?: string;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        WSClientFrame: {
            /**
             * @description Client→Server frames. Only heartbeat.
             * @enum {string}
             */
            type: "ping";
            payload: components["schemas"]["PingPayload"];
        };
        WSServerFrame: {
            /**
             * @description Server→Client frame types.
             * @enum {string}
             */
            type: "updates" | "connected";
            payload: components["schemas"]["ConnectedPayload"] | components["schemas"]["Update"][];
        };
        /** @description Client heartbeat. Sent every 30 seconds. */
        PingPayload: Record<string, never>;
        ConnectedPayload: {
            user_id: string;
            /** Format: date-time */
            server_time: string;
            /** @description Server's current highest seq for this user. */
            max_seq: number;
        };
        /** @description Seq gap filler. No data. */
        EmptyPayload: Record<string, never>;
        MessageNewPayload: {
            /** @description UUID of the conversation. */
            conversation_id: string;
            /** @description UUID of the message. */
            message_id: string;
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            role: "user" | "assistant" | "system" | "tool";
            sender_id: string;
            /** @description Eino callback address string. */
            addr: string;
            /** @description Only present when role is "tool". */
            tool_name?: string;
            /** @description Message content. Present for user messages. */
            content?: string;
        };
        MessageDeltaPayload: {
            conversation_id: string;
            message_id: string;
            /** @description Streaming text chunk. */
            delta: string;
            addr: string;
        };
        MessageDonePayload: {
            conversation_id: string;
            message_id: string;
            role: string;
            sender_id: string;
            /** @description Full final content. */
            content: string;
            /** @description Full reasoning content. */
            reasoning_content: string;
            addr: string;
            /** Format: int64 */
            seq: number;
        };
        MessageToolCallPayload: {
            conversation_id: string;
            message_id: string;
            tool_name: string;
            /** @description Truncated result (max 200 chars). */
            content: string;
            /** Format: int64 */
            seq: number;
            addr: string;
        };
        MessageThinkingPayload: {
            conversation_id: string;
            message_id: string;
            /** @description Streaming reasoning chunk. */
            delta: string;
            addr: string;
        };
        MessageErrorPayload: {
            conversation_id: string;
            error: string;
            /** Format: int64 */
            seq: number;
            /** @description UUID of the interrupted message (optional). */
            message_id?: string;
            /** @description Checkpoint ID for interrupt/resume (optional). */
            checkpoint_id?: string;
        };
        MessageStopPayload: {
            conversation_id: string;
            /** Format: int64 */
            seq: number;
            /** @description UUID of the stopped message (optional). */
            message_id?: string;
        };
        ConversationUpdatedPayload: {
            conversation_id: string;
            /** Format: int64 */
            seq: number;
            title?: string;
            /** @description True if the title was auto-generated by the title agent. */
            title_generated?: boolean;
            /**
             * Format: int64
             * @description Estimated prompt token count for the conversation.
             */
            token_prompt?: number;
            /**
             * Format: int64
             * @description Estimated completion token count for the conversation.
             */
            token_completion?: number;
        };
        ConversationCreatedPayload: {
            /** @description UUID of the conversation. */
            id: string;
            /** @description UUID of the project. */
            project_id: string;
            title?: string;
            status?: string;
            /** Format: int64 */
            seq: number;
        };
        ConversationDeletedPayload: {
            id: string;
            project_id: string;
            /** Format: int64 */
            seq: number;
        };
        ConversationCompactingPayload: {
            /** @description Conversation being compacted */
            conversation_id: string;
            /** Format: int64 */
            seq: number;
        };
        ConversationCompactedPayload: {
            /** @description Original conversation ID */
            old_conv_id: string;
            /** @description New conversation ID after compaction */
            new_conv_id: string;
            /** @description Parent project ID */
            project_id: string;
            /** Format: int64 */
            seq: number;
        };
        ConversationCompressedPayload: {
            /** @description Conversation that was compressed */
            conversation_id: string;
            /**
             * Format: int64
             * @description New compression cursor. Messages below this seq have been compressed.
             */
            min_seq: number;
            /** @description LLM-generated summary of compressed messages */
            summary?: string;
            /** @description ID of the inserted summary message (optional) */
            message_id?: string;
            /** Format: int64 */
            seq: number;
        };
        ConversationArchivedPayload: {
            conversation_id: string;
            /** Format: int64 */
            seq: number;
        };
        ProjectCreatedPayload: {
            /** @description UUID of the project. */
            id: string;
            template_id: string;
            name: string;
            /** Format: int64 */
            seq: number;
        };
        ProjectDeletedPayload: {
            id: string;
            /** Format: int64 */
            seq: number;
        };
        SettingsChangedPayload: {
            /** Format: int64 */
            seq: number;
            /** @enum {string} */
            model_tier: "haiku" | "sonnet" | "opus";
            /** @enum {string} */
            locale: "en" | "zh";
            /** @enum {string} */
            theme: "light" | "dark";
            /** @description Fields that were changed. */
            changed: string[];
        };
        HumanInTheLoop: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            checkpoint_id?: string;
            interrupt_id?: string;
            question: string;
            choices?: {
                title: string;
                desc?: string;
            }[];
            /** @enum {string} */
            answer_type: "single" | "multi" | "text";
            answer?: string | null;
            /** @enum {string} */
            status: "pending" | "answered" | "expired";
            /** Format: date-time */
            created_at: string;
        };
        Todo: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            content: string;
            completed: boolean;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CronTask: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            /** @enum {string} */
            sender_role: "assistant" | "user" | "system" | "tool";
            content: string;
            schedule: string;
            /** Format: date-time */
            next_run_at: string;
            status: string;
            /** Format: date-time */
            created_at: string;
        };
        HumanInPermission: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            checkpoint_id?: string;
            interrupt_id?: string;
            tool_name: string;
            action: string;
            content: string;
            tool_desc?: string;
            args_summary?: string;
            safety_level: number;
            safety_reason?: string;
            /** @enum {string|null} */
            decision?: "approved" | "approved_exact" | "approved_wildcard" | "denied" | null;
            /** @enum {string} */
            status: "pending" | "answered";
            /** Format: date-time */
            created_at: string;
        };
        HumanInTheLoopCreatedPayload: {
            conversation_id: string;
            /** @description HITL request ID */
            id: string;
            /** @description Checkpoint ID for resume */
            checkpoint_id?: string;
            /** @description Interrupt ID for targeted resume */
            interrupt_id?: string;
            question: string;
            choices: {
                title: string;
                desc?: string;
            }[];
            answer_type: string;
            /** Format: int64 */
            seq: number;
        };
        HumanInTheLoopAnsweredPayload: {
            conversation_id: string;
            id: string;
            answer: string;
            /** Format: int64 */
            seq: number;
        };
        PermissionPendingPayload: {
            conversation_id: string;
            permission_id: string;
            tool_name: string;
            action: string;
            content: string;
            tool_desc?: string;
            args_summary?: string;
            safety_level: number;
            safety_reason: string;
            checkpoint_id?: string;
            interrupt_id?: string;
            /** Format: int64 */
            seq: number;
        };
        PermissionDecidedPayload: {
            conversation_id: string;
            permission_id: string;
            /** @enum {string} */
            decision: "approved" | "approved_exact" | "approved_wildcard" | "denied";
            /** Format: int64 */
            seq: number;
        };
        TodoSyncPayload: {
            conversation_id: string;
            /** Format: int64 */
            seq: number;
        };
        CronTaskSyncPayload: {
            conversation_id: string;
            /** Format: int64 */
            seq: number;
        };
        Member: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversation_id: string;
            member_type: string;
            member_id: string;
            member_name?: string;
            is_owner?: boolean;
        };
        Update: {
            /**
             * Format: int64
             * @description > 0 = persisted and replayable. 0 = ephemeral (streaming).
             */
            seq: number;
            /** @enum {string} */
            type: "message.new" | "message.delta" | "message.done" | "message.tool_call" | "message.thinking" | "message.error" | "message.stop" | "human_in_the_loop.created" | "human_in_the_loop.answered" | "todo.sync" | "conversation.created" | "conversation.updated" | "conversation.deleted" | "conversation.compressed" | "conversation.compacting" | "conversation.compacted" | "conversation.archived" | "project.created" | "project.deleted" | "settings.changed" | "empty" | "permission.pending" | "permission.decided" | "cron_task.sync";
            /** @description Type-specific entity. Discriminated by Update.type. Frontend extracts conversation_id from payload to derive topic. */
            payload: components["schemas"]["MessageNewPayload"] | components["schemas"]["MessageDeltaPayload"] | components["schemas"]["MessageDonePayload"] | components["schemas"]["MessageToolCallPayload"] | components["schemas"]["MessageThinkingPayload"] | components["schemas"]["MessageErrorPayload"] | components["schemas"]["MessageStopPayload"] | components["schemas"]["HumanInTheLoopCreatedPayload"] | components["schemas"]["HumanInTheLoopAnsweredPayload"] | components["schemas"]["TodoSyncPayload"] | components["schemas"]["ConversationCreatedPayload"] | components["schemas"]["ConversationUpdatedPayload"] | components["schemas"]["ConversationDeletedPayload"] | components["schemas"]["ConversationCompressedPayload"] | components["schemas"]["ConversationCompactingPayload"] | components["schemas"]["ConversationCompactedPayload"] | components["schemas"]["ConversationArchivedPayload"] | components["schemas"]["ProjectCreatedPayload"] | components["schemas"]["ProjectDeletedPayload"] | components["schemas"]["SettingsChangedPayload"] | components["schemas"]["EmptyPayload"] | components["schemas"]["PermissionPendingPayload"] | components["schemas"]["PermissionDecidedPayload"] | components["schemas"]["CronTaskSyncPayload"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
