/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WSClientFrame: {
            /**
             * @description Client→Server frames. Only heartbeat.
             * @enum {string}
             */
            type: "ping";
            payload: components["schemas"]["PingPayload"];
        };
        WSServerFrame: {
            /**
             * @description Server→Client frame types.
             * @enum {string}
             */
            type: "updates" | "connected";
            payload: components["schemas"]["ConnectedPayload"] | components["schemas"]["Update"][];
        };
        /** @description Client heartbeat. Sent every 30 seconds. */
        PingPayload: Record<string, never>;
        ConnectedPayload: {
            user_id: string;
            /** Format: date-time */
            server_time: string;
            /** @description Server's current highest seq for this user. */
            max_seq: number;
        };
        Update: {
            /** @description > 0 = persisted and replayable. 0 = ephemeral (streaming). */
            seq: number;
            /** @enum {string} */
            type: "message.new" | "message.delta" | "message.done" | "message.tool_call" | "message.thinking" | "message.error" | "message.stop" | "conversation.created" | "conversation.deleted" | "conversation.compacting" | "conversation.compacted" | "conversation.archived" | "project.created" | "project.deleted" | "settings.changed" | "empty";
            /** @description Type-specific entity. Frontend extracts conversation_id from payload to derive topic. */
            payload: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
