// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for UpdateType.
const (
	ConversationArchived   UpdateType = "conversation.archived"
	ConversationCompacted  UpdateType = "conversation.compacted"
	ConversationCompacting UpdateType = "conversation.compacting"
	ConversationCreated    UpdateType = "conversation.created"
	ConversationDeleted    UpdateType = "conversation.deleted"
	Empty                  UpdateType = "empty"
	MessageDelta           UpdateType = "message.delta"
	MessageDone            UpdateType = "message.done"
	MessageError           UpdateType = "message.error"
	MessageNew             UpdateType = "message.new"
	MessageStop            UpdateType = "message.stop"
	MessageThinking        UpdateType = "message.thinking"
	MessageToolCall        UpdateType = "message.tool_call"
	ProjectCreated         UpdateType = "project.created"
	ProjectDeleted         UpdateType = "project.deleted"
	SettingsChanged        UpdateType = "settings.changed"
)

// Valid indicates whether the value is a known member of the UpdateType enum.
func (e UpdateType) Valid() bool {
	switch e {
	case ConversationArchived:
		return true
	case ConversationCompacted:
		return true
	case ConversationCompacting:
		return true
	case ConversationCreated:
		return true
	case ConversationDeleted:
		return true
	case Empty:
		return true
	case MessageDelta:
		return true
	case MessageDone:
		return true
	case MessageError:
		return true
	case MessageNew:
		return true
	case MessageStop:
		return true
	case MessageThinking:
		return true
	case MessageToolCall:
		return true
	case ProjectCreated:
		return true
	case ProjectDeleted:
		return true
	case SettingsChanged:
		return true
	default:
		return false
	}
}

// Defines values for WSClientFrameType.
const (
	Ping WSClientFrameType = "ping"
)

// Valid indicates whether the value is a known member of the WSClientFrameType enum.
func (e WSClientFrameType) Valid() bool {
	switch e {
	case Ping:
		return true
	default:
		return false
	}
}

// Defines values for WSServerFrameType.
const (
	Connected WSServerFrameType = "connected"
	Updates   WSServerFrameType = "updates"
)

// Valid indicates whether the value is a known member of the WSServerFrameType enum.
func (e WSServerFrameType) Valid() bool {
	switch e {
	case Connected:
		return true
	case Updates:
		return true
	default:
		return false
	}
}

// ConnectedPayload defines model for ConnectedPayload.
type ConnectedPayload struct {
	// MaxSeq Server's current highest seq for this user.
	MaxSeq     int       `json:"max_seq"`
	ServerTime time.Time `json:"server_time"`
	UserId     string    `json:"user_id"`
}

// PingPayload Client heartbeat. Sent every 30 seconds.
type PingPayload = map[string]interface{}

// Update defines model for Update.
type Update struct {
	// Payload Type-specific entity. Frontend extracts conversation_id from payload to derive topic.
	Payload map[string]interface{} `json:"payload"`

	// Seq > 0 = persisted and replayable. 0 = ephemeral (streaming).
	Seq  int        `json:"seq"`
	Type UpdateType `json:"type"`
}

// UpdateType defines model for Update.Type.
type UpdateType string

// WSClientFrame defines model for WSClientFrame.
type WSClientFrame struct {
	// Payload Client heartbeat. Sent every 30 seconds.
	Payload PingPayload `json:"payload"`

	// Type Client→Server frames. Only heartbeat.
	Type WSClientFrameType `json:"type"`
}

// WSClientFrameType Client→Server frames. Only heartbeat.
type WSClientFrameType string

// WSServerFrame defines model for WSServerFrame.
type WSServerFrame struct {
	Payload WSServerFrame_Payload `json:"payload"`

	// Type Server→Client frame types.
	Type WSServerFrameType `json:"type"`
}

// WSServerFramePayload1 defines model for .
type WSServerFramePayload1 = []Update

// WSServerFrame_Payload defines model for WSServerFrame.Payload.
type WSServerFrame_Payload struct {
	union json.RawMessage
}

// WSServerFrameType Server→Client frame types.
type WSServerFrameType string

// AsConnectedPayload returns the union data inside the WSServerFrame_Payload as a ConnectedPayload
func (t WSServerFrame_Payload) AsConnectedPayload() (ConnectedPayload, error) {
	var body ConnectedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectedPayload overwrites any union data inside the WSServerFrame_Payload as the provided ConnectedPayload
func (t *WSServerFrame_Payload) FromConnectedPayload(v ConnectedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectedPayload performs a merge with any union data inside the WSServerFrame_Payload, using the provided ConnectedPayload
func (t *WSServerFrame_Payload) MergeConnectedPayload(v ConnectedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWSServerFramePayload1 returns the union data inside the WSServerFrame_Payload as a WSServerFramePayload1
func (t WSServerFrame_Payload) AsWSServerFramePayload1() (WSServerFramePayload1, error) {
	var body WSServerFramePayload1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWSServerFramePayload1 overwrites any union data inside the WSServerFrame_Payload as the provided WSServerFramePayload1
func (t *WSServerFrame_Payload) FromWSServerFramePayload1(v WSServerFramePayload1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWSServerFramePayload1 performs a merge with any union data inside the WSServerFrame_Payload, using the provided WSServerFramePayload1
func (t *WSServerFrame_Payload) MergeWSServerFramePayload1(v WSServerFramePayload1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WSServerFrame_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WSServerFrame_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
