// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package types

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HumanInPermissionDecision.
const (
	HumanInPermissionDecisionApproved         HumanInPermissionDecision = "approved"
	HumanInPermissionDecisionApprovedExact    HumanInPermissionDecision = "approved_exact"
	HumanInPermissionDecisionApprovedWildcard HumanInPermissionDecision = "approved_wildcard"
	HumanInPermissionDecisionDenied           HumanInPermissionDecision = "denied"
)

// Valid indicates whether the value is a known member of the HumanInPermissionDecision enum.
func (e HumanInPermissionDecision) Valid() bool {
	switch e {
	case HumanInPermissionDecisionApproved:
		return true
	case HumanInPermissionDecisionApprovedExact:
		return true
	case HumanInPermissionDecisionApprovedWildcard:
		return true
	case HumanInPermissionDecisionDenied:
		return true
	default:
		return false
	}
}

// Defines values for HumanInPermissionStatus.
const (
	HumanInPermissionStatusAnswered HumanInPermissionStatus = "answered"
	HumanInPermissionStatusPending  HumanInPermissionStatus = "pending"
)

// Valid indicates whether the value is a known member of the HumanInPermissionStatus enum.
func (e HumanInPermissionStatus) Valid() bool {
	switch e {
	case HumanInPermissionStatusAnswered:
		return true
	case HumanInPermissionStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for HumanInTheLoopAnswerType.
const (
	Multi  HumanInTheLoopAnswerType = "multi"
	Single HumanInTheLoopAnswerType = "single"
	Text   HumanInTheLoopAnswerType = "text"
)

// Valid indicates whether the value is a known member of the HumanInTheLoopAnswerType enum.
func (e HumanInTheLoopAnswerType) Valid() bool {
	switch e {
	case Multi:
		return true
	case Single:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for HumanInTheLoopStatus.
const (
	HumanInTheLoopStatusAnswered HumanInTheLoopStatus = "answered"
	HumanInTheLoopStatusExpired  HumanInTheLoopStatus = "expired"
	HumanInTheLoopStatusPending  HumanInTheLoopStatus = "pending"
)

// Valid indicates whether the value is a known member of the HumanInTheLoopStatus enum.
func (e HumanInTheLoopStatus) Valid() bool {
	switch e {
	case HumanInTheLoopStatusAnswered:
		return true
	case HumanInTheLoopStatusExpired:
		return true
	case HumanInTheLoopStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for MessageSenderRole.
const (
	MessageSenderRoleAssistant MessageSenderRole = "assistant"
	MessageSenderRoleSystem    MessageSenderRole = "system"
	MessageSenderRoleTool      MessageSenderRole = "tool"
	MessageSenderRoleUser      MessageSenderRole = "user"
)

// Valid indicates whether the value is a known member of the MessageSenderRole enum.
func (e MessageSenderRole) Valid() bool {
	switch e {
	case MessageSenderRoleAssistant:
		return true
	case MessageSenderRoleSystem:
		return true
	case MessageSenderRoleTool:
		return true
	case MessageSenderRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for MessageNewPayloadRole.
const (
	MessageNewPayloadRoleAssistant MessageNewPayloadRole = "assistant"
	MessageNewPayloadRoleSystem    MessageNewPayloadRole = "system"
	MessageNewPayloadRoleTool      MessageNewPayloadRole = "tool"
	MessageNewPayloadRoleUser      MessageNewPayloadRole = "user"
)

// Valid indicates whether the value is a known member of the MessageNewPayloadRole enum.
func (e MessageNewPayloadRole) Valid() bool {
	switch e {
	case MessageNewPayloadRoleAssistant:
		return true
	case MessageNewPayloadRoleSystem:
		return true
	case MessageNewPayloadRoleTool:
		return true
	case MessageNewPayloadRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PermissionDecidedPayloadDecision.
const (
	PermissionDecidedPayloadDecisionApproved         PermissionDecidedPayloadDecision = "approved"
	PermissionDecidedPayloadDecisionApprovedExact    PermissionDecidedPayloadDecision = "approved_exact"
	PermissionDecidedPayloadDecisionApprovedWildcard PermissionDecidedPayloadDecision = "approved_wildcard"
	PermissionDecidedPayloadDecisionDenied           PermissionDecidedPayloadDecision = "denied"
)

// Valid indicates whether the value is a known member of the PermissionDecidedPayloadDecision enum.
func (e PermissionDecidedPayloadDecision) Valid() bool {
	switch e {
	case PermissionDecidedPayloadDecisionApproved:
		return true
	case PermissionDecidedPayloadDecisionApprovedExact:
		return true
	case PermissionDecidedPayloadDecisionApprovedWildcard:
		return true
	case PermissionDecidedPayloadDecisionDenied:
		return true
	default:
		return false
	}
}

// Defines values for SettingsLocale.
const (
	SettingsLocaleEn SettingsLocale = "en"
	SettingsLocaleZh SettingsLocale = "zh"
)

// Valid indicates whether the value is a known member of the SettingsLocale enum.
func (e SettingsLocale) Valid() bool {
	switch e {
	case SettingsLocaleEn:
		return true
	case SettingsLocaleZh:
		return true
	default:
		return false
	}
}

// Defines values for SettingsModelTier.
const (
	SettingsModelTierHaiku  SettingsModelTier = "haiku"
	SettingsModelTierOpus   SettingsModelTier = "opus"
	SettingsModelTierSonnet SettingsModelTier = "sonnet"
)

// Valid indicates whether the value is a known member of the SettingsModelTier enum.
func (e SettingsModelTier) Valid() bool {
	switch e {
	case SettingsModelTierHaiku:
		return true
	case SettingsModelTierOpus:
		return true
	case SettingsModelTierSonnet:
		return true
	default:
		return false
	}
}

// Defines values for SettingsTheme.
const (
	SettingsThemeDark  SettingsTheme = "dark"
	SettingsThemeLight SettingsTheme = "light"
)

// Valid indicates whether the value is a known member of the SettingsTheme enum.
func (e SettingsTheme) Valid() bool {
	switch e {
	case SettingsThemeDark:
		return true
	case SettingsThemeLight:
		return true
	default:
		return false
	}
}

// Defines values for SettingsChangedPayloadLocale.
const (
	SettingsChangedPayloadLocaleEn SettingsChangedPayloadLocale = "en"
	SettingsChangedPayloadLocaleZh SettingsChangedPayloadLocale = "zh"
)

// Valid indicates whether the value is a known member of the SettingsChangedPayloadLocale enum.
func (e SettingsChangedPayloadLocale) Valid() bool {
	switch e {
	case SettingsChangedPayloadLocaleEn:
		return true
	case SettingsChangedPayloadLocaleZh:
		return true
	default:
		return false
	}
}

// Defines values for SettingsChangedPayloadModelTier.
const (
	SettingsChangedPayloadModelTierHaiku  SettingsChangedPayloadModelTier = "haiku"
	SettingsChangedPayloadModelTierOpus   SettingsChangedPayloadModelTier = "opus"
	SettingsChangedPayloadModelTierSonnet SettingsChangedPayloadModelTier = "sonnet"
)

// Valid indicates whether the value is a known member of the SettingsChangedPayloadModelTier enum.
func (e SettingsChangedPayloadModelTier) Valid() bool {
	switch e {
	case SettingsChangedPayloadModelTierHaiku:
		return true
	case SettingsChangedPayloadModelTierOpus:
		return true
	case SettingsChangedPayloadModelTierSonnet:
		return true
	default:
		return false
	}
}

// Defines values for SettingsChangedPayloadTheme.
const (
	SettingsChangedPayloadThemeDark  SettingsChangedPayloadTheme = "dark"
	SettingsChangedPayloadThemeLight SettingsChangedPayloadTheme = "light"
)

// Valid indicates whether the value is a known member of the SettingsChangedPayloadTheme enum.
func (e SettingsChangedPayloadTheme) Valid() bool {
	switch e {
	case SettingsChangedPayloadThemeDark:
		return true
	case SettingsChangedPayloadThemeLight:
		return true
	default:
		return false
	}
}

// Defines values for TemplateDifficulty.
const (
	Advanced     TemplateDifficulty = "advanced"
	Beginner     TemplateDifficulty = "beginner"
	Intermediate TemplateDifficulty = "intermediate"
)

// Valid indicates whether the value is a known member of the TemplateDifficulty enum.
func (e TemplateDifficulty) Valid() bool {
	switch e {
	case Advanced:
		return true
	case Beginner:
		return true
	case Intermediate:
		return true
	default:
		return false
	}
}

// Defines values for UpdateType.
const (
	ConversationArchived   UpdateType = "conversation.archived"
	ConversationCompacted  UpdateType = "conversation.compacted"
	ConversationCompacting UpdateType = "conversation.compacting"
	ConversationCompressed UpdateType = "conversation.compressed"
	ConversationCreated    UpdateType = "conversation.created"
	ConversationDeleted    UpdateType = "conversation.deleted"
	ConversationUpdated    UpdateType = "conversation.updated"
	Empty                  UpdateType = "empty"
	HumanInTheLoopAnswered UpdateType = "human_in_the_loop.answered"
	HumanInTheLoopCreated  UpdateType = "human_in_the_loop.created"
	MessageDelta           UpdateType = "message.delta"
	MessageDone            UpdateType = "message.done"
	MessageError           UpdateType = "message.error"
	MessageNew             UpdateType = "message.new"
	MessageStop            UpdateType = "message.stop"
	MessageThinking        UpdateType = "message.thinking"
	MessageToolCall        UpdateType = "message.tool_call"
	PermissionDecided      UpdateType = "permission.decided"
	PermissionPending      UpdateType = "permission.pending"
	ProjectCreated         UpdateType = "project.created"
	ProjectDeleted         UpdateType = "project.deleted"
	SettingsChanged        UpdateType = "settings.changed"
	TodoSync               UpdateType = "todo.sync"
)

// Valid indicates whether the value is a known member of the UpdateType enum.
func (e UpdateType) Valid() bool {
	switch e {
	case ConversationArchived:
		return true
	case ConversationCompacted:
		return true
	case ConversationCompacting:
		return true
	case ConversationCompressed:
		return true
	case ConversationCreated:
		return true
	case ConversationDeleted:
		return true
	case ConversationUpdated:
		return true
	case Empty:
		return true
	case HumanInTheLoopAnswered:
		return true
	case HumanInTheLoopCreated:
		return true
	case MessageDelta:
		return true
	case MessageDone:
		return true
	case MessageError:
		return true
	case MessageNew:
		return true
	case MessageStop:
		return true
	case MessageThinking:
		return true
	case MessageToolCall:
		return true
	case PermissionDecided:
		return true
	case PermissionPending:
		return true
	case ProjectCreated:
		return true
	case ProjectDeleted:
		return true
	case SettingsChanged:
		return true
	case TodoSync:
		return true
	default:
		return false
	}
}

// Defines values for WSClientFrameType.
const (
	Ping WSClientFrameType = "ping"
)

// Valid indicates whether the value is a known member of the WSClientFrameType enum.
func (e WSClientFrameType) Valid() bool {
	switch e {
	case Ping:
		return true
	default:
		return false
	}
}

// Defines values for WSServerFrameType.
const (
	Connected WSServerFrameType = "connected"
	Updates   WSServerFrameType = "updates"
)

// Valid indicates whether the value is a known member of the WSServerFrameType enum.
func (e WSServerFrameType) Valid() bool {
	switch e {
	case Connected:
		return true
	case Updates:
		return true
	default:
		return false
	}
}

// Defines values for GetConversationsIdPermissionsParamsStatus.
const (
	Answered GetConversationsIdPermissionsParamsStatus = "answered"
	Pending  GetConversationsIdPermissionsParamsStatus = "pending"
)

// Valid indicates whether the value is a known member of the GetConversationsIdPermissionsParamsStatus enum.
func (e GetConversationsIdPermissionsParamsStatus) Valid() bool {
	switch e {
	case Answered:
		return true
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision.
const (
	Approved         PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision = "approved"
	ApprovedExact    PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision = "approved_exact"
	ApprovedWildcard PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision = "approved_wildcard"
	Denied           PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision = "denied"
)

// Valid indicates whether the value is a known member of the PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision enum.
func (e PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision) Valid() bool {
	switch e {
	case Approved:
		return true
	case ApprovedExact:
		return true
	case ApprovedWildcard:
		return true
	case Denied:
		return true
	default:
		return false
	}
}

// Defines values for PutSettingsJSONBodyLocale.
const (
	En PutSettingsJSONBodyLocale = "en"
	Zh PutSettingsJSONBodyLocale = "zh"
)

// Valid indicates whether the value is a known member of the PutSettingsJSONBodyLocale enum.
func (e PutSettingsJSONBodyLocale) Valid() bool {
	switch e {
	case En:
		return true
	case Zh:
		return true
	default:
		return false
	}
}

// Defines values for PutSettingsJSONBodyModelTier.
const (
	Haiku  PutSettingsJSONBodyModelTier = "haiku"
	Opus   PutSettingsJSONBodyModelTier = "opus"
	Sonnet PutSettingsJSONBodyModelTier = "sonnet"
)

// Valid indicates whether the value is a known member of the PutSettingsJSONBodyModelTier enum.
func (e PutSettingsJSONBodyModelTier) Valid() bool {
	switch e {
	case Haiku:
		return true
	case Opus:
		return true
	case Sonnet:
		return true
	default:
		return false
	}
}

// Defines values for PutSettingsJSONBodyTheme.
const (
	Dark  PutSettingsJSONBodyTheme = "dark"
	Light PutSettingsJSONBodyTheme = "light"
)

// Valid indicates whether the value is a known member of the PutSettingsJSONBodyTheme enum.
func (e PutSettingsJSONBodyTheme) Valid() bool {
	switch e {
	case Dark:
		return true
	case Light:
		return true
	default:
		return false
	}
}

// ConnectedPayload defines model for ConnectedPayload.
type ConnectedPayload struct {
	// MaxSeq Server's current highest seq for this user.
	MaxSeq     int       `json:"max_seq"`
	ServerTime time.Time `json:"server_time"`
	UserId     string    `json:"user_id"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	CreatedAt       *time.Time         `json:"created_at,omitempty"`
	Id              openapi_types.UUID `json:"id"`
	LastPreview     *string            `json:"last_preview,omitempty"`
	LatestSeq       *int               `json:"latest_seq,omitempty"`
	MemberCount     *int               `json:"member_count,omitempty"`
	MessageCount    *int               `json:"message_count,omitempty"`
	ProjectId       openapi_types.UUID `json:"project_id"`
	Status          *string            `json:"status,omitempty"`
	Summary         *string            `json:"summary,omitempty"`
	Title           *string            `json:"title,omitempty"`
	TokenCompletion *int               `json:"token_completion,omitempty"`
	TokenPrompt     *int               `json:"token_prompt,omitempty"`
	UpdatedAt       *time.Time         `json:"updated_at,omitempty"`
	UserId          openapi_types.UUID `json:"user_id"`
}

// ConversationArchivedPayload defines model for ConversationArchivedPayload.
type ConversationArchivedPayload struct {
	ConversationId string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
}

// ConversationCompactedPayload defines model for ConversationCompactedPayload.
type ConversationCompactedPayload struct {
	// NewConvId New conversation ID after compaction
	NewConvId string `json:"new_conv_id"`

	// OldConvId Original conversation ID
	OldConvId string `json:"old_conv_id"`

	// ProjectId Parent project ID
	ProjectId string `json:"project_id"`
	Seq       int64  `json:"seq"`
}

// ConversationCompactingPayload defines model for ConversationCompactingPayload.
type ConversationCompactingPayload struct {
	// ConversationId Conversation being compacted
	ConversationId string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
}

// ConversationCompressedPayload defines model for ConversationCompressedPayload.
type ConversationCompressedPayload struct {
	// ConversationId Conversation that was compressed
	ConversationId string `json:"conversation_id"`

	// MessageId ID of the inserted summary message (optional)
	MessageId *string `json:"message_id,omitempty"`

	// MinSeq New compression cursor. Messages below this seq have been compressed.
	MinSeq int64 `json:"min_seq"`
	Seq    int64 `json:"seq"`

	// Summary LLM-generated summary of compressed messages
	Summary *string `json:"summary,omitempty"`
}

// ConversationCreatedPayload defines model for ConversationCreatedPayload.
type ConversationCreatedPayload struct {
	// Id UUID of the conversation.
	Id string `json:"id"`

	// ProjectId UUID of the project.
	ProjectId string  `json:"project_id"`
	Seq       int64   `json:"seq"`
	Status    *string `json:"status,omitempty"`
	Title     *string `json:"title,omitempty"`
}

// ConversationDeletedPayload defines model for ConversationDeletedPayload.
type ConversationDeletedPayload struct {
	Id        string `json:"id"`
	ProjectId string `json:"project_id"`
	Seq       int64  `json:"seq"`
}

// ConversationUpdatedPayload defines model for ConversationUpdatedPayload.
type ConversationUpdatedPayload struct {
	ConversationId string  `json:"conversation_id"`
	Seq            int64   `json:"seq"`
	Title          *string `json:"title,omitempty"`

	// TitleGenerated True if the title was auto-generated by the title agent.
	TitleGenerated *bool `json:"title_generated,omitempty"`

	// TokenCompletion Estimated completion token count for the conversation.
	TokenCompletion *int64 `json:"token_completion,omitempty"`

	// TokenPrompt Estimated prompt token count for the conversation.
	TokenPrompt *int64 `json:"token_prompt,omitempty"`
}

// EmptyPayload Seq gap filler. No data.
type EmptyPayload = map[string]interface{}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// HumanInPermission defines model for HumanInPermission.
type HumanInPermission struct {
	Action         string                     `json:"action"`
	ArgsSummary    *string                    `json:"args_summary,omitempty"`
	CheckpointId   *string                    `json:"checkpoint_id,omitempty"`
	Content        string                     `json:"content"`
	ConversationId openapi_types.UUID         `json:"conversation_id"`
	CreatedAt      time.Time                  `json:"created_at"`
	Decision       *HumanInPermissionDecision `json:"decision,omitempty"`
	Id             openapi_types.UUID         `json:"id"`
	InterruptId    *string                    `json:"interrupt_id,omitempty"`
	SafetyLevel    int                        `json:"safety_level"`
	SafetyReason   *string                    `json:"safety_reason,omitempty"`
	Status         HumanInPermissionStatus    `json:"status"`
	ToolDesc       *string                    `json:"tool_desc,omitempty"`
	ToolName       string                     `json:"tool_name"`
}

// HumanInPermissionDecision defines model for HumanInPermission.Decision.
type HumanInPermissionDecision string

// HumanInPermissionStatus defines model for HumanInPermission.Status.
type HumanInPermissionStatus string

// HumanInTheLoop defines model for HumanInTheLoop.
type HumanInTheLoop struct {
	Answer       *string                  `json:"answer,omitempty"`
	AnswerType   HumanInTheLoopAnswerType `json:"answer_type"`
	CheckpointId *string                  `json:"checkpoint_id,omitempty"`
	Choices      *[]struct {
		Desc  *string `json:"desc,omitempty"`
		Title string  `json:"title"`
	} `json:"choices,omitempty"`
	ConversationId openapi_types.UUID   `json:"conversation_id"`
	CreatedAt      time.Time            `json:"created_at"`
	Id             openapi_types.UUID   `json:"id"`
	InterruptId    *string              `json:"interrupt_id,omitempty"`
	Question       string               `json:"question"`
	Status         HumanInTheLoopStatus `json:"status"`
}

// HumanInTheLoopAnswerType defines model for HumanInTheLoop.AnswerType.
type HumanInTheLoopAnswerType string

// HumanInTheLoopStatus defines model for HumanInTheLoop.Status.
type HumanInTheLoopStatus string

// HumanInTheLoopAnsweredPayload defines model for HumanInTheLoopAnsweredPayload.
type HumanInTheLoopAnsweredPayload struct {
	Answer         string `json:"answer"`
	ConversationId string `json:"conversation_id"`
	Id             string `json:"id"`
	Seq            int64  `json:"seq"`
}

// HumanInTheLoopCreatedPayload defines model for HumanInTheLoopCreatedPayload.
type HumanInTheLoopCreatedPayload struct {
	AnswerType string `json:"answer_type"`

	// CheckpointId Checkpoint ID for resume
	CheckpointId *string `json:"checkpoint_id,omitempty"`
	Choices      []struct {
		Desc  *string `json:"desc,omitempty"`
		Title string  `json:"title"`
	} `json:"choices"`
	ConversationId string `json:"conversation_id"`

	// Id HITL request ID
	Id string `json:"id"`

	// InterruptId Interrupt ID for targeted resume
	InterruptId *string `json:"interrupt_id,omitempty"`
	Question    string  `json:"question"`
	Seq         int64   `json:"seq"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      *string            `json:"name,omitempty"`
	Settings  Settings           `json:"settings"`
}

// Message defines model for Message.
type Message struct {
	Content          string                  `json:"content"`
	ConversationId   string                  `json:"conversation_id"`
	CreatedAt        *time.Time              `json:"created_at,omitempty"`
	DurationMs       *int                    `json:"duration_ms,omitempty"`
	ErrorMessage     *string                 `json:"error_message,omitempty"`
	FinishReason     *string                 `json:"finish_reason,omitempty"`
	Id               string                  `json:"id"`
	MentionedMembers *[]string               `json:"mentioned_members,omitempty"`
	Metadata         *map[string]interface{} `json:"metadata,omitempty"`
	ReasonContent    *string                 `json:"reason_content,omitempty"`
	ReplyToSeq       *int                    `json:"reply_to_seq,omitempty"`
	SenderId         *string                 `json:"sender_id,omitempty"`
	SenderRole       MessageSenderRole       `json:"sender_role"`
	Seq              int                     `json:"seq"`
	TokenCompletion  *int                    `json:"token_completion,omitempty"`
	TokenPrompt      *int                    `json:"token_prompt,omitempty"`
	ToolCalling      *struct {
		// Input Tool call input arguments
		Input *map[string]interface{} `json:"input,omitempty"`

		// Output Tool call output result
		Output *string `json:"output,omitempty"`
	} `json:"tool_calling,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// MessageSenderRole defines model for Message.SenderRole.
type MessageSenderRole string

// MessageDeltaPayload defines model for MessageDeltaPayload.
type MessageDeltaPayload struct {
	Addr           string `json:"addr"`
	ConversationId string `json:"conversation_id"`

	// Delta Streaming text chunk.
	Delta     string `json:"delta"`
	MessageId string `json:"message_id"`
}

// MessageDonePayload defines model for MessageDonePayload.
type MessageDonePayload struct {
	Addr string `json:"addr"`

	// Content Full final content.
	Content        string `json:"content"`
	ConversationId string `json:"conversation_id"`
	MessageId      string `json:"message_id"`

	// ReasoningContent Full reasoning content.
	ReasoningContent string `json:"reasoning_content"`
	Role             string `json:"role"`
	SenderId         string `json:"sender_id"`
	Seq              int64  `json:"seq"`
}

// MessageErrorPayload defines model for MessageErrorPayload.
type MessageErrorPayload struct {
	// CheckpointId Checkpoint ID for interrupt/resume (optional).
	CheckpointId   *string `json:"checkpoint_id,omitempty"`
	ConversationId string  `json:"conversation_id"`
	Error          string  `json:"error"`

	// MessageId UUID of the interrupted message (optional).
	MessageId *string `json:"message_id,omitempty"`
	Seq       int64   `json:"seq"`
}

// MessageNewPayload defines model for MessageNewPayload.
type MessageNewPayload struct {
	// Addr Eino callback address string.
	Addr string `json:"addr"`

	// Content Message content. Present for user messages.
	Content *string `json:"content,omitempty"`

	// ConversationId UUID of the conversation.
	ConversationId string `json:"conversation_id"`

	// MessageId UUID of the message.
	MessageId string                `json:"message_id"`
	Role      MessageNewPayloadRole `json:"role"`
	SenderId  string                `json:"sender_id"`
	Seq       int64                 `json:"seq"`

	// ToolName Only present when role is "tool".
	ToolName *string `json:"tool_name,omitempty"`
}

// MessageNewPayloadRole defines model for MessageNewPayload.Role.
type MessageNewPayloadRole string

// MessageStopPayload defines model for MessageStopPayload.
type MessageStopPayload struct {
	ConversationId string `json:"conversation_id"`

	// MessageId UUID of the stopped message (optional).
	MessageId *string `json:"message_id,omitempty"`
	Seq       int64   `json:"seq"`
}

// MessageThinkingPayload defines model for MessageThinkingPayload.
type MessageThinkingPayload struct {
	Addr           string `json:"addr"`
	ConversationId string `json:"conversation_id"`

	// Delta Streaming reasoning chunk.
	Delta     string `json:"delta"`
	MessageId string `json:"message_id"`
}

// MessageToolCallPayload defines model for MessageToolCallPayload.
type MessageToolCallPayload struct {
	Addr string `json:"addr"`

	// Content Truncated result (max 200 chars).
	Content        string `json:"content"`
	ConversationId string `json:"conversation_id"`
	MessageId      string `json:"message_id"`
	Seq            int64  `json:"seq"`
	ToolName       string `json:"tool_name"`
}

// PermissionDecidedPayload defines model for PermissionDecidedPayload.
type PermissionDecidedPayload struct {
	ConversationId string                           `json:"conversation_id"`
	Decision       PermissionDecidedPayloadDecision `json:"decision"`
	PermissionId   string                           `json:"permission_id"`
	Seq            int64                            `json:"seq"`
}

// PermissionDecidedPayloadDecision defines model for PermissionDecidedPayload.Decision.
type PermissionDecidedPayloadDecision string

// PermissionPendingPayload defines model for PermissionPendingPayload.
type PermissionPendingPayload struct {
	Action         string  `json:"action"`
	ArgsSummary    *string `json:"args_summary,omitempty"`
	CheckpointId   *string `json:"checkpoint_id,omitempty"`
	Content        string  `json:"content"`
	ConversationId string  `json:"conversation_id"`
	InterruptId    *string `json:"interrupt_id,omitempty"`
	PermissionId   string  `json:"permission_id"`
	SafetyLevel    int     `json:"safety_level"`
	SafetyReason   string  `json:"safety_reason"`
	Seq            int64   `json:"seq"`
	ToolDesc       *string `json:"tool_desc,omitempty"`
	ToolName       string  `json:"tool_name"`
}

// PingPayload Client heartbeat. Sent every 30 seconds.
type PingPayload = map[string]interface{}

// Project defines model for Project.
type Project struct {
	Config     *map[string]interface{} `json:"config,omitempty"`
	CreatedAt  *time.Time              `json:"created_at,omitempty"`
	Id         openapi_types.UUID      `json:"id"`
	Name       string                  `json:"name"`
	TemplateId string                  `json:"template_id"`
	UserId     openapi_types.UUID      `json:"user_id"`
}

// ProjectCreatedPayload defines model for ProjectCreatedPayload.
type ProjectCreatedPayload struct {
	// Id UUID of the project.
	Id         string `json:"id"`
	Name       string `json:"name"`
	Seq        int64  `json:"seq"`
	TemplateId string `json:"template_id"`
}

// ProjectDeletedPayload defines model for ProjectDeletedPayload.
type ProjectDeletedPayload struct {
	Id  string `json:"id"`
	Seq int64  `json:"seq"`
}

// Settings defines model for Settings.
type Settings struct {
	Locale    *SettingsLocale    `json:"locale,omitempty"`
	ModelTier *SettingsModelTier `json:"model_tier,omitempty"`
	Theme     *SettingsTheme     `json:"theme,omitempty"`
	UpdatedAt *time.Time         `json:"updated_at,omitempty"`
}

// SettingsLocale defines model for Settings.Locale.
type SettingsLocale string

// SettingsModelTier defines model for Settings.ModelTier.
type SettingsModelTier string

// SettingsTheme defines model for Settings.Theme.
type SettingsTheme string

// SettingsChangedPayload defines model for SettingsChangedPayload.
type SettingsChangedPayload struct {
	// Changed Fields that were changed.
	Changed   []string                        `json:"changed"`
	Locale    SettingsChangedPayloadLocale    `json:"locale"`
	ModelTier SettingsChangedPayloadModelTier `json:"model_tier"`
	Seq       int64                           `json:"seq"`
	Theme     SettingsChangedPayloadTheme     `json:"theme"`
}

// SettingsChangedPayloadLocale defines model for SettingsChangedPayload.Locale.
type SettingsChangedPayloadLocale string

// SettingsChangedPayloadModelTier defines model for SettingsChangedPayload.ModelTier.
type SettingsChangedPayloadModelTier string

// SettingsChangedPayloadTheme defines model for SettingsChangedPayload.Theme.
type SettingsChangedPayloadTheme string

// Template defines model for Template.
type Template struct {
	Description string              `json:"description"`
	Difficulty  *TemplateDifficulty `json:"difficulty,omitempty"`
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Tags        *[]string           `json:"tags,omitempty"`
}

// TemplateDifficulty defines model for Template.Difficulty.
type TemplateDifficulty string

// Todo defines model for Todo.
type Todo struct {
	Completed      bool                    `json:"completed"`
	Content        string                  `json:"content"`
	ConversationId openapi_types.UUID      `json:"conversation_id"`
	CreatedAt      time.Time               `json:"created_at"`
	Id             openapi_types.UUID      `json:"id"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	UpdatedAt      time.Time               `json:"updated_at"`
}

// TodoSyncPayload defines model for TodoSyncPayload.
type TodoSyncPayload struct {
	ConversationId string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
}

// Update defines model for Update.
type Update struct {
	// Payload Type-specific entity. Discriminated by Update.type. Frontend extracts conversation_id from payload to derive topic.
	Payload Update_Payload `json:"payload"`

	// Seq > 0 = persisted and replayable. 0 = ephemeral (streaming).
	Seq  int64      `json:"seq"`
	Type UpdateType `json:"type"`
}

// Update_Payload Type-specific entity. Discriminated by Update.type. Frontend extracts conversation_id from payload to derive topic.
type Update_Payload struct {
	union json.RawMessage
}

// UpdateType defines model for Update.Type.
type UpdateType string

// User defines model for User.
type User struct {
	AvatarUrl *string            `json:"avatar_url,omitempty"`
	CreatedAt *time.Time         `json:"created_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	Name      *string            `json:"name,omitempty"`
}

// WSClientFrame defines model for WSClientFrame.
type WSClientFrame struct {
	// Payload Client heartbeat. Sent every 30 seconds.
	Payload PingPayload `json:"payload"`

	// Type Client→Server frames. Only heartbeat.
	Type WSClientFrameType `json:"type"`
}

// WSClientFrameType Client→Server frames. Only heartbeat.
type WSClientFrameType string

// WSServerFrame defines model for WSServerFrame.
type WSServerFrame struct {
	Payload WSServerFrame_Payload `json:"payload"`

	// Type Server→Client frame types.
	Type WSServerFrameType `json:"type"`
}

// WSServerFramePayload1 defines model for .
type WSServerFramePayload1 = []Update

// WSServerFrame_Payload defines model for WSServerFrame.Payload.
type WSServerFrame_Payload struct {
	union json.RawMessage
}

// WSServerFrameType Server→Client frame types.
type WSServerFrameType string

// PatchConversationsIdJSONBody defines parameters for PatchConversationsId.
type PatchConversationsIdJSONBody struct {
	// Title New conversation title
	Title string `json:"title"`
}

// PostConversationsIdAnswerJSONBody defines parameters for PostConversationsIdAnswer.
type PostConversationsIdAnswerJSONBody struct {
	// Answer User's answer text
	Answer string `json:"answer"`

	// CheckpointId Eino checkpoint ID for resuming the agent run
	CheckpointId string `json:"checkpoint_id"`

	// InterruptId Eino interrupt signal ID for targeted resume
	InterruptId string `json:"interrupt_id"`
}

// PostConversationsIdMessagesJSONBody defines parameters for PostConversationsIdMessages.
type PostConversationsIdMessagesJSONBody struct {
	Content string `json:"content"`
}

// GetConversationsIdPermissionsParams defines parameters for GetConversationsIdPermissions.
type GetConversationsIdPermissionsParams struct {
	Status *GetConversationsIdPermissionsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// GetConversationsIdPermissionsParamsStatus defines parameters for GetConversationsIdPermissions.
type GetConversationsIdPermissionsParamsStatus string

// PostConversationsIdPermissionsPermIdAnswerJSONBody defines parameters for PostConversationsIdPermissionsPermIdAnswer.
type PostConversationsIdPermissionsPermIdAnswerJSONBody struct {
	CheckpointId string                                                     `json:"checkpoint_id"`
	Decision     PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision `json:"decision"`
	InterruptId  string                                                     `json:"interrupt_id"`
}

// PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision defines parameters for PostConversationsIdPermissionsPermIdAnswer.
type PostConversationsIdPermissionsPermIdAnswerJSONBodyDecision string

// PostConversationsIdTodosJSONBody defines parameters for PostConversationsIdTodos.
type PostConversationsIdTodosJSONBody struct {
	Content string `json:"content"`
}

// PutProjectsIdJSONBody defines parameters for PutProjectsId.
type PutProjectsIdJSONBody struct {
	Config *map[string]interface{} `json:"config,omitempty"`
	Name   *string                 `json:"name,omitempty"`
}

// PostProjectsIdConversationsJSONBody defines parameters for PostProjectsIdConversations.
type PostProjectsIdConversationsJSONBody struct {
	Title *string `json:"title,omitempty"`
}

// PutSettingsJSONBody defines parameters for PutSettings.
type PutSettingsJSONBody struct {
	Locale    *PutSettingsJSONBodyLocale    `json:"locale,omitempty"`
	ModelTier *PutSettingsJSONBodyModelTier `json:"model_tier,omitempty"`
	Theme     *PutSettingsJSONBodyTheme     `json:"theme,omitempty"`
}

// PutSettingsJSONBodyLocale defines parameters for PutSettings.
type PutSettingsJSONBodyLocale string

// PutSettingsJSONBodyModelTier defines parameters for PutSettings.
type PutSettingsJSONBodyModelTier string

// PutSettingsJSONBodyTheme defines parameters for PutSettings.
type PutSettingsJSONBodyTheme string

// PostTemplatesIdProjectsJSONBody defines parameters for PostTemplatesIdProjects.
type PostTemplatesIdProjectsJSONBody = map[string]interface{}

// PatchTodosIdJSONBody defines parameters for PatchTodosId.
type PatchTodosIdJSONBody struct {
	Completed *bool   `json:"completed,omitempty"`
	Content   *string `json:"content,omitempty"`
}

// GetUsersMeUpdatesParams defines parameters for GetUsersMeUpdates.
type GetUsersMeUpdatesParams struct {
	LastSeq *int64 `form:"last_seq,omitempty" json:"last_seq,omitempty"`
}

// PatchConversationsIdJSONRequestBody defines body for PatchConversationsId for application/json ContentType.
type PatchConversationsIdJSONRequestBody PatchConversationsIdJSONBody

// PostConversationsIdAnswerJSONRequestBody defines body for PostConversationsIdAnswer for application/json ContentType.
type PostConversationsIdAnswerJSONRequestBody PostConversationsIdAnswerJSONBody

// PostConversationsIdMessagesJSONRequestBody defines body for PostConversationsIdMessages for application/json ContentType.
type PostConversationsIdMessagesJSONRequestBody PostConversationsIdMessagesJSONBody

// PostConversationsIdPermissionsPermIdAnswerJSONRequestBody defines body for PostConversationsIdPermissionsPermIdAnswer for application/json ContentType.
type PostConversationsIdPermissionsPermIdAnswerJSONRequestBody PostConversationsIdPermissionsPermIdAnswerJSONBody

// PostConversationsIdTodosJSONRequestBody defines body for PostConversationsIdTodos for application/json ContentType.
type PostConversationsIdTodosJSONRequestBody PostConversationsIdTodosJSONBody

// PutProjectsIdJSONRequestBody defines body for PutProjectsId for application/json ContentType.
type PutProjectsIdJSONRequestBody PutProjectsIdJSONBody

// PostProjectsIdConversationsJSONRequestBody defines body for PostProjectsIdConversations for application/json ContentType.
type PostProjectsIdConversationsJSONRequestBody PostProjectsIdConversationsJSONBody

// PutSettingsJSONRequestBody defines body for PutSettings for application/json ContentType.
type PutSettingsJSONRequestBody PutSettingsJSONBody

// PostTemplatesIdProjectsJSONRequestBody defines body for PostTemplatesIdProjects for application/json ContentType.
type PostTemplatesIdProjectsJSONRequestBody = PostTemplatesIdProjectsJSONBody

// PatchTodosIdJSONRequestBody defines body for PatchTodosId for application/json ContentType.
type PatchTodosIdJSONRequestBody PatchTodosIdJSONBody

// AsMessageNewPayload returns the union data inside the Update_Payload as a MessageNewPayload
func (t Update_Payload) AsMessageNewPayload() (MessageNewPayload, error) {
	var body MessageNewPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageNewPayload overwrites any union data inside the Update_Payload as the provided MessageNewPayload
func (t *Update_Payload) FromMessageNewPayload(v MessageNewPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageNewPayload performs a merge with any union data inside the Update_Payload, using the provided MessageNewPayload
func (t *Update_Payload) MergeMessageNewPayload(v MessageNewPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageDeltaPayload returns the union data inside the Update_Payload as a MessageDeltaPayload
func (t Update_Payload) AsMessageDeltaPayload() (MessageDeltaPayload, error) {
	var body MessageDeltaPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageDeltaPayload overwrites any union data inside the Update_Payload as the provided MessageDeltaPayload
func (t *Update_Payload) FromMessageDeltaPayload(v MessageDeltaPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageDeltaPayload performs a merge with any union data inside the Update_Payload, using the provided MessageDeltaPayload
func (t *Update_Payload) MergeMessageDeltaPayload(v MessageDeltaPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageDonePayload returns the union data inside the Update_Payload as a MessageDonePayload
func (t Update_Payload) AsMessageDonePayload() (MessageDonePayload, error) {
	var body MessageDonePayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageDonePayload overwrites any union data inside the Update_Payload as the provided MessageDonePayload
func (t *Update_Payload) FromMessageDonePayload(v MessageDonePayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageDonePayload performs a merge with any union data inside the Update_Payload, using the provided MessageDonePayload
func (t *Update_Payload) MergeMessageDonePayload(v MessageDonePayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageToolCallPayload returns the union data inside the Update_Payload as a MessageToolCallPayload
func (t Update_Payload) AsMessageToolCallPayload() (MessageToolCallPayload, error) {
	var body MessageToolCallPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageToolCallPayload overwrites any union data inside the Update_Payload as the provided MessageToolCallPayload
func (t *Update_Payload) FromMessageToolCallPayload(v MessageToolCallPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageToolCallPayload performs a merge with any union data inside the Update_Payload, using the provided MessageToolCallPayload
func (t *Update_Payload) MergeMessageToolCallPayload(v MessageToolCallPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageThinkingPayload returns the union data inside the Update_Payload as a MessageThinkingPayload
func (t Update_Payload) AsMessageThinkingPayload() (MessageThinkingPayload, error) {
	var body MessageThinkingPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageThinkingPayload overwrites any union data inside the Update_Payload as the provided MessageThinkingPayload
func (t *Update_Payload) FromMessageThinkingPayload(v MessageThinkingPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageThinkingPayload performs a merge with any union data inside the Update_Payload, using the provided MessageThinkingPayload
func (t *Update_Payload) MergeMessageThinkingPayload(v MessageThinkingPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageErrorPayload returns the union data inside the Update_Payload as a MessageErrorPayload
func (t Update_Payload) AsMessageErrorPayload() (MessageErrorPayload, error) {
	var body MessageErrorPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageErrorPayload overwrites any union data inside the Update_Payload as the provided MessageErrorPayload
func (t *Update_Payload) FromMessageErrorPayload(v MessageErrorPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageErrorPayload performs a merge with any union data inside the Update_Payload, using the provided MessageErrorPayload
func (t *Update_Payload) MergeMessageErrorPayload(v MessageErrorPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMessageStopPayload returns the union data inside the Update_Payload as a MessageStopPayload
func (t Update_Payload) AsMessageStopPayload() (MessageStopPayload, error) {
	var body MessageStopPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageStopPayload overwrites any union data inside the Update_Payload as the provided MessageStopPayload
func (t *Update_Payload) FromMessageStopPayload(v MessageStopPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageStopPayload performs a merge with any union data inside the Update_Payload, using the provided MessageStopPayload
func (t *Update_Payload) MergeMessageStopPayload(v MessageStopPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHumanInTheLoopCreatedPayload returns the union data inside the Update_Payload as a HumanInTheLoopCreatedPayload
func (t Update_Payload) AsHumanInTheLoopCreatedPayload() (HumanInTheLoopCreatedPayload, error) {
	var body HumanInTheLoopCreatedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHumanInTheLoopCreatedPayload overwrites any union data inside the Update_Payload as the provided HumanInTheLoopCreatedPayload
func (t *Update_Payload) FromHumanInTheLoopCreatedPayload(v HumanInTheLoopCreatedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHumanInTheLoopCreatedPayload performs a merge with any union data inside the Update_Payload, using the provided HumanInTheLoopCreatedPayload
func (t *Update_Payload) MergeHumanInTheLoopCreatedPayload(v HumanInTheLoopCreatedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsHumanInTheLoopAnsweredPayload returns the union data inside the Update_Payload as a HumanInTheLoopAnsweredPayload
func (t Update_Payload) AsHumanInTheLoopAnsweredPayload() (HumanInTheLoopAnsweredPayload, error) {
	var body HumanInTheLoopAnsweredPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromHumanInTheLoopAnsweredPayload overwrites any union data inside the Update_Payload as the provided HumanInTheLoopAnsweredPayload
func (t *Update_Payload) FromHumanInTheLoopAnsweredPayload(v HumanInTheLoopAnsweredPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeHumanInTheLoopAnsweredPayload performs a merge with any union data inside the Update_Payload, using the provided HumanInTheLoopAnsweredPayload
func (t *Update_Payload) MergeHumanInTheLoopAnsweredPayload(v HumanInTheLoopAnsweredPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTodoSyncPayload returns the union data inside the Update_Payload as a TodoSyncPayload
func (t Update_Payload) AsTodoSyncPayload() (TodoSyncPayload, error) {
	var body TodoSyncPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTodoSyncPayload overwrites any union data inside the Update_Payload as the provided TodoSyncPayload
func (t *Update_Payload) FromTodoSyncPayload(v TodoSyncPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTodoSyncPayload performs a merge with any union data inside the Update_Payload, using the provided TodoSyncPayload
func (t *Update_Payload) MergeTodoSyncPayload(v TodoSyncPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationCreatedPayload returns the union data inside the Update_Payload as a ConversationCreatedPayload
func (t Update_Payload) AsConversationCreatedPayload() (ConversationCreatedPayload, error) {
	var body ConversationCreatedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationCreatedPayload overwrites any union data inside the Update_Payload as the provided ConversationCreatedPayload
func (t *Update_Payload) FromConversationCreatedPayload(v ConversationCreatedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationCreatedPayload performs a merge with any union data inside the Update_Payload, using the provided ConversationCreatedPayload
func (t *Update_Payload) MergeConversationCreatedPayload(v ConversationCreatedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationUpdatedPayload returns the union data inside the Update_Payload as a ConversationUpdatedPayload
func (t Update_Payload) AsConversationUpdatedPayload() (ConversationUpdatedPayload, error) {
	var body ConversationUpdatedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationUpdatedPayload overwrites any union data inside the Update_Payload as the provided ConversationUpdatedPayload
func (t *Update_Payload) FromConversationUpdatedPayload(v ConversationUpdatedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationUpdatedPayload performs a merge with any union data inside the Update_Payload, using the provided ConversationUpdatedPayload
func (t *Update_Payload) MergeConversationUpdatedPayload(v ConversationUpdatedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationDeletedPayload returns the union data inside the Update_Payload as a ConversationDeletedPayload
func (t Update_Payload) AsConversationDeletedPayload() (ConversationDeletedPayload, error) {
	var body ConversationDeletedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationDeletedPayload overwrites any union data inside the Update_Payload as the provided ConversationDeletedPayload
func (t *Update_Payload) FromConversationDeletedPayload(v ConversationDeletedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationDeletedPayload performs a merge with any union data inside the Update_Payload, using the provided ConversationDeletedPayload
func (t *Update_Payload) MergeConversationDeletedPayload(v ConversationDeletedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationCompressedPayload returns the union data inside the Update_Payload as a ConversationCompressedPayload
func (t Update_Payload) AsConversationCompressedPayload() (ConversationCompressedPayload, error) {
	var body ConversationCompressedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationCompressedPayload overwrites any union data inside the Update_Payload as the provided ConversationCompressedPayload
func (t *Update_Payload) FromConversationCompressedPayload(v ConversationCompressedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationCompressedPayload performs a merge with any union data inside the Update_Payload, using the provided ConversationCompressedPayload
func (t *Update_Payload) MergeConversationCompressedPayload(v ConversationCompressedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationCompactingPayload returns the union data inside the Update_Payload as a ConversationCompactingPayload
func (t Update_Payload) AsConversationCompactingPayload() (ConversationCompactingPayload, error) {
	var body ConversationCompactingPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationCompactingPayload overwrites any union data inside the Update_Payload as the provided ConversationCompactingPayload
func (t *Update_Payload) FromConversationCompactingPayload(v ConversationCompactingPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationCompactingPayload performs a merge with any union data inside the Update_Payload, using the provided ConversationCompactingPayload
func (t *Update_Payload) MergeConversationCompactingPayload(v ConversationCompactingPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationCompactedPayload returns the union data inside the Update_Payload as a ConversationCompactedPayload
func (t Update_Payload) AsConversationCompactedPayload() (ConversationCompactedPayload, error) {
	var body ConversationCompactedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationCompactedPayload overwrites any union data inside the Update_Payload as the provided ConversationCompactedPayload
func (t *Update_Payload) FromConversationCompactedPayload(v ConversationCompactedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationCompactedPayload performs a merge with any union data inside the Update_Payload, using the provided ConversationCompactedPayload
func (t *Update_Payload) MergeConversationCompactedPayload(v ConversationCompactedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConversationArchivedPayload returns the union data inside the Update_Payload as a ConversationArchivedPayload
func (t Update_Payload) AsConversationArchivedPayload() (ConversationArchivedPayload, error) {
	var body ConversationArchivedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConversationArchivedPayload overwrites any union data inside the Update_Payload as the provided ConversationArchivedPayload
func (t *Update_Payload) FromConversationArchivedPayload(v ConversationArchivedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConversationArchivedPayload performs a merge with any union data inside the Update_Payload, using the provided ConversationArchivedPayload
func (t *Update_Payload) MergeConversationArchivedPayload(v ConversationArchivedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProjectCreatedPayload returns the union data inside the Update_Payload as a ProjectCreatedPayload
func (t Update_Payload) AsProjectCreatedPayload() (ProjectCreatedPayload, error) {
	var body ProjectCreatedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProjectCreatedPayload overwrites any union data inside the Update_Payload as the provided ProjectCreatedPayload
func (t *Update_Payload) FromProjectCreatedPayload(v ProjectCreatedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProjectCreatedPayload performs a merge with any union data inside the Update_Payload, using the provided ProjectCreatedPayload
func (t *Update_Payload) MergeProjectCreatedPayload(v ProjectCreatedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProjectDeletedPayload returns the union data inside the Update_Payload as a ProjectDeletedPayload
func (t Update_Payload) AsProjectDeletedPayload() (ProjectDeletedPayload, error) {
	var body ProjectDeletedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProjectDeletedPayload overwrites any union data inside the Update_Payload as the provided ProjectDeletedPayload
func (t *Update_Payload) FromProjectDeletedPayload(v ProjectDeletedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProjectDeletedPayload performs a merge with any union data inside the Update_Payload, using the provided ProjectDeletedPayload
func (t *Update_Payload) MergeProjectDeletedPayload(v ProjectDeletedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSettingsChangedPayload returns the union data inside the Update_Payload as a SettingsChangedPayload
func (t Update_Payload) AsSettingsChangedPayload() (SettingsChangedPayload, error) {
	var body SettingsChangedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSettingsChangedPayload overwrites any union data inside the Update_Payload as the provided SettingsChangedPayload
func (t *Update_Payload) FromSettingsChangedPayload(v SettingsChangedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSettingsChangedPayload performs a merge with any union data inside the Update_Payload, using the provided SettingsChangedPayload
func (t *Update_Payload) MergeSettingsChangedPayload(v SettingsChangedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmptyPayload returns the union data inside the Update_Payload as a EmptyPayload
func (t Update_Payload) AsEmptyPayload() (EmptyPayload, error) {
	var body EmptyPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmptyPayload overwrites any union data inside the Update_Payload as the provided EmptyPayload
func (t *Update_Payload) FromEmptyPayload(v EmptyPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmptyPayload performs a merge with any union data inside the Update_Payload, using the provided EmptyPayload
func (t *Update_Payload) MergeEmptyPayload(v EmptyPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPermissionPendingPayload returns the union data inside the Update_Payload as a PermissionPendingPayload
func (t Update_Payload) AsPermissionPendingPayload() (PermissionPendingPayload, error) {
	var body PermissionPendingPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPermissionPendingPayload overwrites any union data inside the Update_Payload as the provided PermissionPendingPayload
func (t *Update_Payload) FromPermissionPendingPayload(v PermissionPendingPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePermissionPendingPayload performs a merge with any union data inside the Update_Payload, using the provided PermissionPendingPayload
func (t *Update_Payload) MergePermissionPendingPayload(v PermissionPendingPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPermissionDecidedPayload returns the union data inside the Update_Payload as a PermissionDecidedPayload
func (t Update_Payload) AsPermissionDecidedPayload() (PermissionDecidedPayload, error) {
	var body PermissionDecidedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPermissionDecidedPayload overwrites any union data inside the Update_Payload as the provided PermissionDecidedPayload
func (t *Update_Payload) FromPermissionDecidedPayload(v PermissionDecidedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePermissionDecidedPayload performs a merge with any union data inside the Update_Payload, using the provided PermissionDecidedPayload
func (t *Update_Payload) MergePermissionDecidedPayload(v PermissionDecidedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Update_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Update_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsConnectedPayload returns the union data inside the WSServerFrame_Payload as a ConnectedPayload
func (t WSServerFrame_Payload) AsConnectedPayload() (ConnectedPayload, error) {
	var body ConnectedPayload
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConnectedPayload overwrites any union data inside the WSServerFrame_Payload as the provided ConnectedPayload
func (t *WSServerFrame_Payload) FromConnectedPayload(v ConnectedPayload) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConnectedPayload performs a merge with any union data inside the WSServerFrame_Payload, using the provided ConnectedPayload
func (t *WSServerFrame_Payload) MergeConnectedPayload(v ConnectedPayload) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWSServerFramePayload1 returns the union data inside the WSServerFrame_Payload as a WSServerFramePayload1
func (t WSServerFrame_Payload) AsWSServerFramePayload1() (WSServerFramePayload1, error) {
	var body WSServerFramePayload1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWSServerFramePayload1 overwrites any union data inside the WSServerFrame_Payload as the provided WSServerFramePayload1
func (t *WSServerFrame_Payload) FromWSServerFramePayload1(v WSServerFramePayload1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWSServerFramePayload1 performs a merge with any union data inside the WSServerFrame_Payload, using the provided WSServerFramePayload1
func (t *WSServerFrame_Payload) MergeWSServerFramePayload1(v WSServerFramePayload1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t WSServerFrame_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *WSServerFrame_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
